# Задание numpy

In [1]:
import numpy as np

#test case
import testerMF
from testerMF.testerMF import Tester 
testcase = Tester(userId="№№№№" , day='1')

Соединение установлено


In [2]:
y_pred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
y = np.array([1, 0, 0, 1, 1])

### 1. $L_1$ норма
Напишите функцию, которая для двух векторов вычисляет их $L_1$ норму ("манхэттенское расстояние" или "расстояние городских кварталов"):
$$\begin{align*} & L_1(y_{pred}, y) = \sum_{i=0}^m|y^{(i)} - y_{pred}^{(i)}| \end{align*}$$  

In [5]:
def L1_norm(y_pred, y):
    
    """
        YOUR CODE HERE
    """ 
    
    return 

In [6]:
print("L1 = " + str(L1_norm(y_pred,y)))

testcase.sendTask(part='2', task='1', func=L1_norm)

L1 = 1.1
Решение отправлено на проверку
Начало тест кейса, получаем данные...
Tests OK


### 2. $L_2$ норма
Напишите функцию, которая для двух векторов вычисляет их $L_2$ норму (евклидово расстояние):
$$\begin{align*} & L_2(y_{pred},y) = \sum_{i=0}^m(y^{(i)} - y_{pred}^{(i)})^2 \end{align*}$$

In [10]:
def L2_norm(y_pred, y):
    
    """
        YOUR CODE HERE
    """ 
    
    
    return

In [11]:
print("L2 = " + str(L2_norm(y_pred,y)))

testcase.sendTask(part='2', task='2', func=L2_norm)

L2 = None
Решение отправлено на проверку
Начало тест кейса, получаем данные...
Test Case пройден


ConnectionRefusedError: [Errno 111] Connection refused

### 3.* Неуникальные строки
Напишите функцию, которая для 2-мерной матрицы произвольного размера возвращает все строки, содержащие только одинаковые значения (напр. [2, 2, 2, 2])

In [7]:
np.random.seed(777)
Z = np.random.randint(0,5,(6,5))
Z_eq = np.array((np.ones(5), np.zeros(5)))
Z = np.vstack((Z, Z_eq))
print(Z)

[[3. 1. 4. 1. 2.]
 [0. 2. 0. 3. 1.]
 [2. 4. 1. 3. 2.]
 [2. 2. 4. 0. 2.]
 [2. 4. 0. 0. 0.]
 [3. 2. 2. 0. 3.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [8]:
def non_unique(X):
        
    """
        YOUR CODE HERE
    """ 
    
    
    return 

In [9]:
print("Equal items rows: \n", non_unique(Z))


testcase.sendTask(part='2', task='3', func=non_unique)

Equal items rows: 
 [[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
